"""Export the rule tables so both scoring engines read one source.

`packages/core` scores in Python; `web/companion` scores in JavaScript so it works
with no backend (NFR-04). Two implementations of L3 is what AC-1 and AC-5 exist to
prevent, and it has already cost once — the COLD_GUARD lived in one engine and not
the other for a whole build.

This does not merge the engines. It removes the thing that actually drifts: the
constants. The JavaScript reads generated rules rather than its own literals, so a
threshold can only be changed in one place.

Behaviour is covered separately by the parity corpus, which is a set of inputs with
Python's answers attached, for the JavaScript to check itself against.

    uv run python -m core.export
"""

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from contracts import AgeBand, Condition, ExposureFeatures, MedClass, Person, Tier
from core.corpus import Corpus
from core.rules import EXPOSURE_RULES, HEATING_DAY_MAX, VULNERABILITY_RULES, VulnKind
from core.scoring import RiskScorer
from core.vulnerability import VulnerabilityScorer

WEB_SHARED = Path(__file__).resolve().parents[4] / "web" / "shared"
RULES_PATH = WEB_SHARED / "rules.generated.json"
CORPUS_PATH = WEB_SHARED / "parity-corpus.generated.json"

APP_GENERATED = (
    Path(__file__).resolve().parents[4] / "web" / "app" / "src" / "generated"
)
CLINICAL_PATH = APP_GENERATED / "clinical.generated.json"
"""The subset the Next.js app needs: medication class weights and the interaction
rules. Written into its source tree so it is a typed import rather than a fetch —
the app must work offline, and a fetch would make the clinical content the first
thing to disappear when the network does."""

BANNER = "GENERATED by core.export — do not edit. Run: uv run python -m core.export"


@dataclass(frozen=True, slots=True)
class ParityCase:
    """One scenario with Python's answer attached, for the other engine to check."""

    name: str
    exposure: ExposureFeatures
    person: Person


class RuleExporter:
    """Serialises the declarative rule tables and a parity corpus."""

    def __init__(self, corpus: Corpus) -> None:
        self.corpus = corpus
        self.scorer = RiskScorer(corpus)
        self.vulnerability = VulnerabilityScorer()

    def rules_document(self) -> dict[str, Any]:
        return {
            "_banner": BANNER,
            "heating_day_max": HEATING_DAY_MAX,
            "tier_thresholds": [
                {"floor": floor, "tier": tier.name.title()}
                for floor, tier in RiskScorer.THRESHOLDS
            ],
            "exposure_rules": [
                {
                    "code": rule.code.name,
                    "weight": rule.weight,
                    "title": self.corpus.reasons[rule.code].title,
                    "why": self.corpus.reasons[rule.code].explanation,
                    "bounds": [
                        {
                            "field": bound.field,
                            "minimum": bound.minimum,
                            "maximum": bound.maximum,
                        }
                        for bound in rule.bounds
                    ],
                }
                for rule in EXPOSURE_RULES
            ],
            "vulnerability_rules": [
                {
                    "code": rule.code.name,
                    "weight": rule.weight,
                    "kind": rule.kind.value,
                    "value": str(rule.value),
                    "title": self.corpus.reasons[rule.code].title,
                    "why": self.corpus.reasons[rule.code].explanation,
                }
                for rule in VULNERABILITY_RULES
            ],
            "med_classes": {
                name: med_class.value
                for name, med_class in sorted(self.corpus.med_classes.items())
            },
            "med_class_weights": {
                rule.value: rule.weight
                for rule in VULNERABILITY_RULES
                if rule.kind is VulnKind.MED_CLASS
            },
            "interactions": self.interaction_rules(),
        }

    @staticmethod
    def interaction_rules() -> list[dict[str, Any]]:
        """The clinical content the TypeScript app has no equivalent of.

        Its profile carries one `medication` checkbox worth a couple of degrees.
        That cannot distinguish lithium — where dehydration is a toxicity risk and
        the spec's single heaviest vulnerability weight — from a beta blocker. Nor
        can it express a combination, which is where the advice that matters lives.
        """
        # Local import by necessity: actions depends on core.corpus, so a
        # top-level import here would close the cycle.
        from actions.interactions import InteractionTable

        return [
            {
                "code": rule.code,
                "min_peak_air": rule.min_peak_air,
                "max_indoor_day": rule.max_indoor_day,
                "requires_conditions": sorted(c.value for c in rule.requires_conditions),
                "requires_med_classes": sorted(
                    m.value for m in rule.requires_med_classes
                ),
                "requires_flags": sorted(rule.requires_flags),
                "requires_self_report": (
                    None
                    if rule.requires_self_report is None
                    else {
                        "field": rule.requires_self_report[0],
                        "expected": rule.requires_self_report[1],
                    }
                ),
                "min_tier": rule.min_tier.name.title(),
                "advice_caregiver": rule.advice_caregiver,
                "advice_person": rule.advice_person,
                "watch_for": rule.watch_for,
                "escalate_to": rule.escalate_to,
                "supersedes": sorted(c.value for c in rule.supersedes),
            }
            for rule in InteractionTable.load().rules
        ]

    @staticmethod
    def cases() -> tuple[ParityCase, ...]:
        """Scenarios chosen to pin the boundaries, not the comfortable middle.

        Each one is a case where the two engines could plausibly disagree: a tier
        edge, the FR-18 short-circuit, the COLD_GUARD, and the section 8.6 example.
        """
        from datetime import date

        from contracts import AlertLevel, ExposureSource, Med

        def exposure(**kw) -> ExposureFeatures:
            base = dict(
                date=date(2025, 7, 19), overnight_min=12.0, peak_apparent=18.0,
                peak_air=18.0, hours_above_26=0, indoor_night_est=19.0,
                indoor_day_est=21.0, spell_day=0,
                alert_level=AlertLevel.NOT_CHECKED, source=ExposureSource.FIXTURE,
            )
            return ExposureFeatures(**(base | kw))

        def person(**kw) -> Person:
            base = dict(
                id="case", name="Case", age_band=AgeBand.UNDER_65,
                lives_alone=False, mobility_limited=False,
            )
            return Person(**(base | kw))

        doris = person(
            id="doris", age_band=AgeBand.B85_PLUS, lives_alone=True,
            conditions=(Condition.DEMENTIA,),
            medications=(
                Med("furosemide", MedClass.DIURETIC),
                Med("ramipril", MedClass.ACE_ARB),
            ),
        )
        return (
            ParityCase(
                "spec_8_6_worked_example",
                exposure(overnight_min=17.0, peak_apparent=29.0, peak_air=29.0,
                         hours_above_26=7, indoor_night_est=24.6,
                         indoor_day_est=25.85, spell_day=3),
                doris,
            ),
            ParityCase("zero_exposure_frail_person_stays_low", exposure(), doris),
            ParityCase(
                "cold_guard_suppresses_on_a_mild_day",
                exposure(peak_air=19.0, peak_apparent=19.0, indoor_day_est=16.5),
                person(age_band=AgeBand.B85_PLUS),
            ),
            ParityCase(
                "cold_codes_fire_in_genuine_cold",
                exposure(peak_air=7.0, peak_apparent=7.0, overnight_min=2.0,
                         indoor_night_est=6.0, indoor_day_est=6.95),
                person(age_band=AgeBand.B85_PLUS),
            ),
            ParityCase(
                "bedroom_band_lower_edge",
                exposure(indoor_night_est=24.0), person(age_band=AgeBand.B85_PLUS),
            ),
            ParityCase(
                "bedroom_band_upper_edge_is_unsafe",
                exposure(indoor_night_est=26.0), person(age_band=AgeBand.B85_PLUS),
            ),
            ParityCase(
                "sustained_spell_needs_both_bounds",
                exposure(spell_day=3, peak_apparent=23.9),
                person(age_band=AgeBand.B85_PLUS),
            ),
        )

    def corpus_document(self) -> dict[str, Any]:
        cases = []
        for case in self.cases():
            profile = self.vulnerability.profile(case.person)
            assessment = self.scorer.assess(case.exposure, profile)
            cases.append(
                {
                    "name": case.name,
                    "exposure": {
                        "overnight_min": case.exposure.overnight_min,
                        "peak_apparent": case.exposure.peak_apparent,
                        "peak_air": case.exposure.peak_air,
                        "indoor_night_est": case.exposure.indoor_night_est,
                        "indoor_day_est": case.exposure.indoor_day_est,
                        "spell_day": case.exposure.spell_day,
                    },
                    "person": {
                        "age_band": case.person.age_band.value,
                        "lives_alone": case.person.lives_alone,
                        "mobility_limited": case.person.mobility_limited,
                        "conditions": [c.value for c in case.person.conditions],
                        "med_classes": sorted(
                            {m.drug_class.value for m in case.person.medications}
                        ),
                    },
                    "expected": {
                        "tier": assessment.tier.name.title(),
                        "risk_score": round(assessment.risk_score, 4),
                        "exposure_score": assessment.exposure_score,
                        "vulnerability_score": assessment.vulnerability_score,
                        "codes": sorted(r.code.name for r in assessment.reasons),
                    },
                }
            )
        return {"_banner": BANNER, "cases": cases}

    @staticmethod
    def render(document: dict[str, Any]) -> str:
        return json.dumps(document, indent=2, sort_keys=False) + "\n"

    def clinical_document(self) -> dict[str, Any]:
        rules = self.rules_document()
        return {
            "_banner": BANNER,
            "med_classes": rules["med_classes"],
            "med_class_weights": rules["med_class_weights"],
            "interactions": rules["interactions"],
        }

    def write(self) -> tuple[Path, ...]:
        WEB_SHARED.mkdir(parents=True, exist_ok=True)
        APP_GENERATED.mkdir(parents=True, exist_ok=True)
        RULES_PATH.write_text(self.render(self.rules_document()))
        CORPUS_PATH.write_text(self.render(self.corpus_document()))
        CLINICAL_PATH.write_text(self.render(self.clinical_document()))
        return RULES_PATH, CORPUS_PATH, CLINICAL_PATH


def main() -> None:
    for path in RuleExporter(Corpus.load()).write():
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
