"""Export the interaction rules for the front end.

Lives here rather than in `core.export` because `actions` depends on `core`, so
`core` cannot depend on `actions` without a circular package dependency. That
cycle existed briefly, dodged with a function-local import — which hid it from
the manifests while leaving `core.export` unable to run without `actions`
installed.

    uv run python -m actions.export
"""

import json
from pathlib import Path
from typing import Any

from actions.interactions import InteractionTable

APP_GENERATED = (
    Path(__file__).resolve().parents[4] / "web" / "app" / "src" / "generated"
)
CLINICAL_PATH = APP_GENERATED / "clinical.generated.json"

BANNER = "GENERATED by actions.export — do not edit. Run: uv run python -m actions.export"


class ClinicalExporter:
    """The clinical content the TypeScript app has no equivalent of.

    Its profile carries one medication checkbox. That cannot distinguish lithium,
    where dehydration is a toxicity risk and which is the heaviest single
    vulnerability in the specification, from a beta blocker. Nor can a flat list
    express a combination, which is where the advice that matters lives.
    """

    def __init__(self, table: InteractionTable, med_classes: dict[str, str],
                 med_class_weights: dict[str, int]) -> None:
        self.table = table
        self.med_classes = med_classes
        self.med_class_weights = med_class_weights

    @classmethod
    def load(cls) -> "ClinicalExporter":
        # Imported here rather than at module scope only to keep the dependency
        # one-directional in the manifests as well as at runtime.
        from core.corpus import Corpus
        from core.rules import VULNERABILITY_RULES, VulnKind

        corpus = Corpus.load()
        return cls(
            table=InteractionTable.load(),
            med_classes={
                name: med_class.value
                for name, med_class in sorted(corpus.med_classes.items())
            },
            med_class_weights={
                rule.value: rule.weight
                for rule in VULNERABILITY_RULES
                if rule.kind is VulnKind.MED_CLASS
            },
        )

    def document(self) -> dict[str, Any]:
        return {
            "_banner": BANNER,
            "med_classes": self.med_classes,
            "med_class_weights": self.med_class_weights,
            "interactions": [
                {
                    "code": rule.code,
                    "min_peak_air": rule.min_peak_air,
                    "max_indoor_day": rule.max_indoor_day,
                    "requires_conditions": sorted(
                        c.value for c in rule.requires_conditions
                    ),
                    "requires_med_classes": sorted(
                        m.value for m in rule.requires_med_classes
                    ),
                    "requires_flags": sorted(rule.requires_flags),
                    "requires_self_report": (
                        None
                        if rule.requires_self_report is None
                        else {
                            "field": rule.requires_self_report[0],
                            "expected": rule.requires_self_report[1],
                        }
                    ),
                    "min_tier": rule.min_tier.name.title(),
                    "advice_caregiver": rule.advice_caregiver,
                    "advice_person": rule.advice_person,
                    "watch_for": rule.watch_for,
                    "escalate_to": rule.escalate_to,
                    "supersedes": sorted(c.value for c in rule.supersedes),
                }
                for rule in self.table.rules
            ],
        }

    def render(self) -> str:
        return json.dumps(self.document(), indent=2, sort_keys=False) + "\n"

    def write(self) -> Path:
        APP_GENERATED.mkdir(parents=True, exist_ok=True)
        CLINICAL_PATH.write_text(self.render())
        return CLINICAL_PATH


def main() -> None:
    print(f"wrote {ClinicalExporter.load().write()}")


if __name__ == "__main__":
    main()
