"""Export the question bank for the front end.

The questionnaire is personalised by selection from a validated bank, never by
generation — see checkin.questions. That property only holds if the front end
selects from the same bank, so the rows are exported rather than retyped.

    uv run python -m checkin.export
"""

import json
from pathlib import Path
from typing import Any

from checkin.questions import QuestionBank

APP_GENERATED = Path(__file__).resolve().parents[4] / "web" / "app" / "src" / "generated"
QUESTIONS_PATH = APP_GENERATED / "questions.generated.json"

BANNER = "GENERATED by checkin.export — do not edit. Run: uv run python -m checkin.export"


class QuestionExporter:
    def __init__(self, bank: QuestionBank) -> None:
        self.bank = bank

    @classmethod
    def load(cls) -> "QuestionExporter":
        return cls(QuestionBank.load())

    def document(self) -> dict[str, Any]:
        return {
            "_banner": BANNER,
            "max_by_tier": {
                tier.name.title(): cap for tier, cap in QuestionBank.MAX_BY_TIER.items()
            },
            "simple_register_max": QuestionBank.SIMPLE_REGISTER_MAX,
            "questions": [
                {
                    "code": row.code,
                    "reason_code": row.reason_code.value if row.reason_code else None,
                    "tier_min": row.tier_min.name.title(),
                    "text": row.text,
                    "text_simple": row.text_simple,
                    "answer_field": row.answer_field,
                    "red_flag": row.red_flag.value if row.red_flag else None,
                    "red_flag_when": row.red_flag_when,
                    "ordering": row.ordering,
                }
                for row in self.bank.rows
            ],
        }

    def render(self) -> str:
        return json.dumps(self.document(), indent=2, sort_keys=False) + "\n"

    def write(self) -> Path:
        APP_GENERATED.mkdir(parents=True, exist_ok=True)
        QUESTIONS_PATH.write_text(self.render())
        return QUESTIONS_PATH


def main() -> None:
    print(f"wrote {QuestionExporter.load().write()}")


if __name__ == "__main__":
    main()
